patchedDependencies:
  '@types/node@22.14.1': patches/@types__node@22.14.1.patch

onlyBuiltDependencies:
  - '@fortawesome/fontawesome-common-types'
  - '@fortawesome/fontawesome-svg-core'
  - '@fortawesome/free-brands-svg-icons'
  - '@fortawesome/free-regular-svg-icons'
  - '@fortawesome/free-solid-svg-icons'
  - '@swc/core'
  - electron
  - esbuild
  - register-scheme
