#!/bin/bash

set -e

unset "AT_SPI_BUS_ADDRES" "container" "DBUS_SESSION_BUS_ADDRESS" "DBUS_SYSTEM_BUS_ADDRESS" "DISPLAY" "LD_LIBRARY_PATH" "LD_PRELOAD" "MEMORY_PRESSURE_WATCH" "PULSE_CLIENTCONFIG" "PULSE_SERVER" "SHELL" "SHELL_SESSION_ID" "XAUTHORITY" "XDG_CACHE_HOME" "XDG_CONFIG_DIRS" "XDG_CONFIG_HOME" "XDG_DATA_DIRS" "XDG_DATA_HOME" "XDG_STATE_HOME" "ZYPAK_BIN" "ZYPAK_LIB"

env_args=()

while read -r -d '' line; do
    [[ "$line" != PATH=* ]] && env_args+=(--env="$line")
done < <(env -0)

if [ -v ENABLE_VK_LAYER_VALVE_steam_overlay_1 ]; then
    env_args+=(--env="LD_PRELOAD=${STEAM_BASE_FOLDER:-$HOME/.local/share/Steam}/ubuntu12_32/gameoverlayrenderer.so:${STEAM_BASE_FOLDER:-$HOME/.local/share/Steam}/ubuntu12_64/gameoverlayrenderer.so")
fi

flatpak-spawn --watch-bus --host "${env_args[@]}" "$@" &
child_pid=$!

cleanup() {
    kill $child_pid 2>/dev/null
    [ -v PROTONPATH ] && [ -v WINEPREFIX ] && flatpak-spawn --host --env=WINEPREFIX=${WINEPREFIX} ${PROTONPATH}/files/bin/wineserver -k
    exit
}
trap cleanup EXIT SIGINT SIGTERM

wait $child_pid
